---
title: "p8105_hw3_jz3570"
author: "Jiawen Zhao"
date: "10/10/2022"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
library (tidyverse)
accel <- read.csv("data/accel_data.csv")
accel <- janitor::clean_names(accel)
accel <- na.omit(accel)
accel <- mutate(accel, weekday_vs_weekend = case_when(day == "Monday" ~ 'weekday', day == "Tuesday" ~ 'weekday',day ==  "Wednesday" ~ 'weekday', day == "Thursday" ~ 'weekday', day == "Friday" ~ 'weekday', day == "Sunday" ~ 'weekend',day == "Saturday" ~ 'weekend'),  .after = day)
accel[,5:1444] <- sapply(accel[,5:1444], as.double)
accel[,1:4] <- sapply(accel[,1:4], as.character)
accel = mutate(accel,Total = rowSums(accel[5:1444]),  .after = day)
## Traditional analyses of accelerometer data focus on the total activity over the day. Using your tidied dataset, aggregate across minutes to create a total activity variable for each day, and create a table showing these totals???????. Are any trends apparent????????



une = 
  pivot_longer(
    accel, 
    activity_1:activity_1440,
    names_to = "time", 
    values_to = "usage")

ggplot(une, aes(x = time, y = usage)) + 
  geom_point(aes(color = day_id, size = 4))+
  geom_line()+ 
  geom_smooth(se = FALSE)
```

```{r}
library(p8105.datasets)
data("ny_noaa")
# clean data???????
## remove na???????
ny_noaa <- separate(ny_noaa, date, into = c("year", "month", "day"), sep = '-')
ny_noaa[,2:4] <- sapply(ny_noaa[,2:4], as.integer)
ny_noaa[,5:9] <- sapply(ny_noaa[,5:9], as.double)
ny_noaa <- mutate(ny_noaa, snow = snow/10, snwd = snwd/10, prcp = prcp/100, tmax = tmax/10, tmin = tmin/10)
tail(names(sort(table(ny_noaa$snow))), 1) ## most common value is 0.


jan = filter(ny_noaa, month == 1)
ave_tmax_jan = aggregate(tmax ~ year, jan, mean) ## average tmax for each year's jan

july = filter(ny_noaa, month == 7)
ave_tmax_july = aggregate(tmax ~ year, july, mean)## average tmax for each year's july

ave_tmax_jan$m_id <- "Jan"
ave_tmax_july$m_id <- "July"

tmax_sum <- rbind(ave_tmax_jan, ave_tmax_july)


ggplot(tmax_sum, aes(x = year, y = tmax, color = m_id)) + 
  geom_point(alpha = .5) +
  facet_grid(. ~ m_id)

tmax = ny_noaa$tmax
tmin = ny_noaa$tmin
tmax = data.frame(tmax)
tmin = data.frame(tmin)
colnames(tmax) <- "temp"
colnames(tmin) <- "temp"
tmax$type = "max"
tmin$type = "min"
tmax$id = ny_noaa$id
tmin$id = ny_noaa$id

max_min <- rbind(tmax, tmin)

ggplot(max_min, aes(x = id, y = temp, color = type)) + 
  geom_point(alpha = .5) +
  facet_grid(. ~ type)+
  geom_smooth(se = FALSE)



#what's x and y here?//??????
```